
genesis-file="/data/genesis.json"

p2p-host="0.0.0.0"
p2p-port="30303"
p2p-enabled=true

bootnodes=[
"enode://1e3194bec11f3143666814ab774e8b1ff7d6048978ff4bddd50eccc0d33af2d6baad614c07ec14f58b68ff238e2a279598b0a4c400703524ec4cfa060bc71111@172.19.0.2:30303"
]

discovery-enabled=true

rpc-http-enabled=true
rpc-http-host="0.0.0.0"
rpc-http-port=8545
rpc-http-cors-origins=["*"]
rpc-http-api=["ADMIN","ETH", "CLIQUE", "NET", "TRACE", "DEBUG", "TXPOOL", "PERM"]
host-allowlist=["*"]


